Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,8 +11,31 @@ on:
 
 
 jobs:
+  
+  # Verifies the tag version is valid
+  # Allowed format is prefix "v" and alphanumeric characters.
+  # Examples: v0.1.0, v0.1.0-alpha, v0.1.0-RELEASE
+  verify:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - uses: olegtarasov/get-tag@v2
+      id: version
+      with:
+        tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
+        tagRegexGroup: 1 # Optional. Default is 1.
+    - name: Abort release
+      if: steps.version.outputs.tag == null
+      run: | 
+        echo "Tag name is invalid."
+        echo "Expected: v*"
+        echo "But found: ${GITHUB_REF##*/}"
+        exit 1
+        
+  # Builds java project with Maven and generate artifact
   build:
     runs-on: ubuntu-latest
+    needs: verify
     steps:
     - uses: actions/checkout@v2
     - uses: actions/cache@v1
@@ -24,6 +47,10 @@ jobs:
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
+    - name: Get release version
+      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
+    - name: Update pom.xml version
+      run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }}
     - name: Build with Maven
       run: mvn -B package --file pom.xml
     - name: Get jar filename
@@ -33,6 +60,8 @@ jobs:
       with:
         name: java-artifact
         path:  ${{ env.JAR_FILE }}
+  
+  # Builds a docker image and pushes it to DockerHub.
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -43,10 +72,13 @@ jobs:
       with:
         name: java-artifact
         path: target
+    - name: Get release version
+      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
     - name: Build, Tag, Publish Docker
       uses: HurricanKai/Publish-Docker-Github-Action@1.12.1
       with:
         name: flashk/armahaleus-telegram-bot
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
+        tags: "latest,${{ env.RELEASE_VERSION }}"
     
